export function createInitialState(preset) {
  return {
    schemaVersion: 2,
    boot: { phase: "press-play", ready: true },
    transport: { status: "stopped", rampEnabled: true },
    soundscape: { id: preset.id, name: preset.name, loaded: false, loading: false, error: null },
    availableSoundscapes: ["SS01", "SS02"],
    tracks: preset.tracks.map((track) => ({
      name: track.name,
      assetId: track.assetId,
      volume: track.volume,
      pan: track.pan ?? 0,
      filter: track.filter ?? 0,
      mute: false,
      solo: false,
      xfade: track.xfade ?? 1,
      frequency: Math.max(1, Math.min(10, Number(track.frequency) || 1)),
      frequencyMode: ["loop", "frequency", "dropout"].includes(track.frequencyMode) ? track.frequencyMode : "loop",
      frequencyRandom: Boolean(track.frequencyRandom),
      loaded: false,
      duration: 0
    })),
    effects: preset.effects,
    character: preset.character,
    tapeType: preset.tapeType,
    frs: preset.frs,
    intensity: preset.intensity,
    autoMix: { enabled: true, active: false, eventCount: 0, lastMove: "—", moving: [], channelLevel: "MED", characterLevel: "MED" },
    autoFx: { enabled: false, active: false, countMode: "1", frequency: "MED", activeEffects: [], lastEffects: [], baselines: {} },
    fxMod: {
      enabled: preset.fxMod?.enabled ?? true,
      hold: preset.fxMod?.hold ?? "normal",
      timeMode: preset.fxMod?.timeMode ?? "01", // legacy compatibility
      probMode: preset.fxMod?.probMode ?? "x1",
      attackMs: Math.max(250, Math.min(8000, Number(preset.fxMod?.attackMs) || 1800)),
      flightMs: Math.max(500, Math.min(12000, Number(preset.fxMod?.flightMs) || 4000)),
      releaseMs: Math.max(500, Math.min(12000, Number(preset.fxMod?.releaseMs) || 4000)),
      infinite: Boolean(preset.fxMod?.infinite ?? (preset.fxMod?.timeMode === "INF")),
      influence: ["LOW","MED","HIGH"].includes(String(preset.fxMod?.influence || "MED").toUpperCase()) ? String(preset.fxMod?.influence || "MED").toUpperCase() : "MED",
      manualOverrideCount: 0,
      memoryX: preset.fxMod?.memoryX ?? 0,
      memoryY: preset.fxMod?.memoryY ?? 0,
      trajectory: Array.isArray(preset.fxMod?.trajectory) ? preset.fxMod.trajectory.map((p) => ({ t: Number(p?.t) || 0, x: Number(p?.x) || 0, y: Number(p?.y) || 0 })) : [],
      releaseVelocity: { x: Number(preset.fxMod?.releaseVelocity?.x) || 0, y: Number(preset.fxMod?.releaseVelocity?.y) || 0 },
      scopeEpochMs: 0,
      scopeCycleMs: 3200,
      scopePassCount: 0,
      params: {intensity:true,reverb:true,width:true,tremolo:true,delay:true,filter:true,...(preset.fxMod?.params||{})},
      active: false,
      stage: "IDLE",
      source: null,
      x: 0,
      y: 0,
      count: 0
    },
    specialEvent: { active: false, stage: "IDLE", count: 0, source: null },
    master: { volume: 0.50, tone: 0, brightness: 1, outputMode: "stereo", muted: false },
    auxiliary: { gameVolume: 0.40, muteSounds: false },
    timer: { selectedMinutes: 0, remainingMs: 0, runIntent: "stopped", expiring: false },
    game: { screen: "inactive", gameId: null, loadingScreenEnabled: false, level: 1 },
    tv: { active: false },
    display: { baseScreen: "welcome", secondary: null, osd: null },
    dev: { enabled: true, engineStatus: "not-initialised", contextState: "—", message: "Ready. Press PLAY to initialise audio and load SS01. Auto Mix is ON and starts with transport." }
  };
}
